#!/bin/bash
#
# Auto Update Script for Ubuntu Server
# Configures automatic weekly system updates with customizable schedule
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

LOG_FILE="/var/log/auto-update-setup.log"
CONFIG_FILE="/etc/crusty-auto-update.conf"
CRON_FILE="/etc/cron.d/crusty-auto-update"

# Logging function
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

log_warn() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING:${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR:${NC} $1" | tee -a "$LOG_FILE"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

# Function to prompt user for update time with input validation
prompt_update_time() {
    local hour
    local minute
    local valid=false

    echo ""
    echo -e "${YELLOW}=== Automatic Update Schedule Configuration ===${NC}"
    echo ""
    echo "Please specify when you'd like automatic updates to run."
    echo "Enter time in 24-hour format (HH:MM), e.g., 02:00 for 2:00 AM"
    echo ""

    while [[ "$valid" == false ]]; do
        read -rp "Enter update time (HH:MM): " time_input

        # Check if input matches HH:MM format
        if [[ "$time_input" =~ ^([0-9]{1,2}):([0-9]{2})$ ]]; then
            hour="${BASH_REMATCH[1]}"
            minute="${BASH_REMATCH[2]}"

            # Validate hour (0-23)
            if [[ "$hour" -ge 0 && "$hour" -le 23 ]]; then
                # Validate minute (0-59)
                if [[ "$minute" -ge 0 && "$minute" -le 59 ]]; then
                    valid=true
                else
                    log_error "Invalid minutes. Please enter a value between 00 and 59."
                fi
            else
                log_error "Invalid hour. Please enter a value between 00 and 23."
            fi
        else
            log_error "Invalid format. Please use HH:MM format (e.g., 02:00, 14:30)"
        fi
    done

    # Format with leading zeros
    printf -v UPDATE_HOUR "%02d" "$hour"
    printf -v UPDATE_MINUTE "%02d" "$minute"

    echo ""
    log "Update time set to: ${UPDATE_HOUR}:${UPDATE_MINUTE}"
}

# Function to save configuration
save_config() {
    log "Saving configuration to $CONFIG_FILE..."
    cat > "$CONFIG_FILE" << EOF
# Crusty System Auto-Update Configuration
# Generated on $(date)
UPDATE_HOUR="$UPDATE_HOUR"
UPDATE_MINUTE="$UPDATE_MINUTE"
UPDATE_DAY="0"
EOF
    chmod 644 "$CONFIG_FILE"
}

# Function to load configuration
load_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
    else
        UPDATE_HOUR="02"
        UPDATE_MINUTE="00"
        UPDATE_DAY="0"
    fi
}

# Function to create cron job
create_cron_job() {
    log "Creating weekly update cron job for ${UPDATE_HOUR}:${UPDATE_MINUTE}..."
    cat > "$CRON_FILE" << EOF
# Crusty System - Weekly automatic updates at ${UPDATE_HOUR}:${UPDATE_MINUTE}
# Generated by auto-update.sh on $(date)
${UPDATE_MINUTE} ${UPDATE_HOUR} * * 0 root /usr/bin/apt-get update && /usr/bin/apt-get upgrade -y >> /var/log/crusty-update.log 2>&1
EOF
    chmod 644 "$CRON_FILE"

    # Create log file with proper permissions
    touch /var/log/crusty-update.log
    chmod 644 /var/log/crusty-update.log
}

# Function to configure unattended-upgrades
configure_unattended_upgrades() {
    log "Installing unattended-upgrades..."
    apt-get install -y -qq unattended-upgrades

    log "Configuring automatic updates..."

    # Create 20auto-upgrades configuration
    cat > /etc/apt/apt.conf.d/20auto-upgrades << EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
EOF

    # Configure unattended-upgrades
    cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

Unattended-Upgrade::Package-Blacklist {
    // Add packages to exclude from automatic updates
};

Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF
}

# Function to run updates immediately
run_updates_now() {
    echo ""
    log "Starting immediate system update..."
    echo ""

    local update_log="/var/log/crusty-update-$(date +%Y%m%d-%H%M%S).log"

    echo -e "${YELLOW}Running: apt-get update${NC}"
    if apt-get update 2>&1 | tee -a "$update_log"; then
        echo -e "${GREEN}Package list updated successfully.${NC}"
    else
        log_error "Failed to update package list."
        return 1
    fi

    echo ""
    echo -e "${YELLOW}Running: apt-get upgrade -y${NC}"
    if apt-get upgrade -y 2>&1 | tee -a "$update_log"; then
        echo -e "${GREEN}System packages upgraded successfully.${NC}"
    else
        log_error "Failed to upgrade packages."
        return 1
    fi

    echo ""
    log "Update completed. Log saved to: $update_log"
}

# Function to prompt for immediate update
prompt_run_now() {
    echo ""
    echo -e "${YELLOW}=== Run Updates Now ===${NC}"
    echo ""
    read -rp "Would you like to run system updates now? [y/N]: " run_now

    if [[ "$run_now" =~ ^[Yy]$ ]]; then
        run_updates_now
    else
        log "Skipping immediate update."
    fi
}

# Function to uninstall auto-updates
uninstall_auto_updates() {
    log "Starting uninstallation of auto-update configuration..."

    # Remove cron job
    if [[ -f "$CRON_FILE" ]]; then
        log "Removing cron job: $CRON_FILE"
        rm -f "$CRON_FILE"
    else
        log_warn "Cron job not found at $CRON_FILE"
    fi

    # Remove config file
    if [[ -f "$CONFIG_FILE" ]]; then
        log "Removing configuration file: $CONFIG_FILE"
        rm -f "$CONFIG_FILE"
    else
        log_warn "Configuration file not found at $CONFIG_FILE"
    fi

    # Remove apt configuration files created by this script
    if [[ -f "/etc/apt/apt.conf.d/20auto-upgrades" ]]; then
        log "Removing apt configuration: 20auto-upgrades"
        rm -f /etc/apt/apt.conf.d/20auto-upgrades
    fi

    if [[ -f "/etc/apt/apt.conf.d/50unattended-upgrades" ]]; then
        log "Removing apt configuration: 50unattended-upgrades"
        rm -f /etc/apt/apt.conf.d/50unattended-upgrades
    fi

    # Optionally remove log files
    echo ""
    read -rp "Would you like to remove log files as well? [y/N]: " remove_logs
    if [[ "$remove_logs" =~ ^[Yy]$ ]]; then
        log "Removing log files..."
        rm -f /var/log/crusty-update.log
        rm -f /var/log/crusty-update-*.log
        rm -f "$LOG_FILE"
    fi

    echo ""
    echo "=========================================="
    log "Uninstallation Complete!"
    echo "=========================================="
    echo ""
    echo -e "${GREEN}Removed:${NC}"
    echo "  - Cron job: $CRON_FILE"
    echo "  - Configuration: $CONFIG_FILE"
    echo "  - APT auto-upgrade settings"
    echo ""
    echo -e "${YELLOW}Note:${NC} The 'unattended-upgrades' package was not removed."
    echo "      To remove it, run: apt-get remove unattended-upgrades"
    echo ""
}

# Function to display current configuration
show_config() {
    echo ""
    echo "=========================================="
    echo -e "${GREEN}Current Auto-Update Configuration${NC}"
    echo "=========================================="
    echo ""

    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
        echo -e "${GREEN}Schedule:${NC}"
        echo "  - Day: Sunday (weekly)"
        echo "  - Time: ${UPDATE_HOUR}:${UPDATE_MINUTE}"
        echo ""
    else
        echo -e "${YELLOW}No configuration file found.${NC}"
    fi

    if [[ -f "$CRON_FILE" ]]; then
        echo -e "${GREEN}Cron Job:${NC}"
        grep -v "^#" "$CRON_FILE" | head -1
        echo ""
    else
        echo -e "${YELLOW}No cron job found.${NC}"
    fi

    echo -e "${GREEN}APT Configuration:${NC}"
    if [[ -f "/etc/apt/apt.conf.d/20auto-upgrades" ]]; then
        echo "  - 20auto-upgrades: Present"
    else
        echo "  - 20auto-upgrades: Not present"
    fi

    if [[ -f "/etc/apt/apt.conf.d/50unattended-upgrades" ]]; then
        echo "  - 50unattended-upgrades: Present"
    else
        echo "  - 50unattended-upgrades: Not present"
    fi
    echo ""
}

# Function to display usage
show_usage() {
    echo "Usage: $0 [OPTION]"
    echo ""
    echo "Options:"
    echo "  install     Install and configure auto-updates (default)"
    echo "  uninstall   Remove auto-update configuration and files"
    echo "  status      Show current auto-update configuration"
    echo "  run-now     Trigger system updates immediately"
    echo "  --help      Show this help message"
    echo ""
    echo "Examples:"
    echo "  sudo $0 install"
    echo "  sudo $0 uninstall"
    echo "  sudo $0 run-now"
    echo ""
}

# Main installation function
install_auto_updates() {
    log "Starting Auto Update Setup..."

    # Prompt for update time
    prompt_update_time

    # Save configuration
    save_config

    # Configure unattended-upgrades
    configure_unattended_upgrades

    # Create cron job
    create_cron_job

    # Display summary
    echo ""
    echo "=========================================="
    log "Auto Update Setup Complete!"
    echo "=========================================="
    echo ""
    echo -e "${GREEN}Configuration Summary:${NC}"
    echo "  - Update Schedule: Weekly at ${UPDATE_HOUR}:${UPDATE_MINUTE} (Sunday)"
    echo "  - Unattended-upgrades: Enabled"
    echo "  - Security updates: Automatic"
    echo "  - Package cleanup: Weekly"
    echo ""
    echo -e "${YELLOW}Log Files:${NC}"
    echo "  - Setup log: $LOG_FILE"
    echo "  - Update log: /var/log/crusty-update.log"
    echo ""
    echo -e "${GREEN}Configuration Files:${NC}"
    echo "  - Config: $CONFIG_FILE"
    echo "  - Cron: $CRON_FILE"
    echo ""

    # Ask if user wants to run updates now
    prompt_run_now

    echo ""
    echo -e "${GREEN}To manually trigger an update later, run:${NC}"
    echo "  $0 run-now"
    echo ""
}

# Main script logic
main() {
    check_root

    case "${1:-install}" in
        install)
            install_auto_updates
            ;;
        uninstall)
            uninstall_auto_updates
            ;;
        status)
            show_config
            ;;
        run-now)
            run_updates_now
            ;;
        --help|-h)
            show_usage
            ;;
        *)
            log_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
}

main "$@"
