#!/bin/bash
#
# SSH Hardener Script for Ubuntu Server
# Configures SSH security, firewall, fail2ban, and automatic updates
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
SSH_PORT=58432
BACKUP_DIR="/root/crusty-backups-$(date +%Y%m%d_%H%M%S)"
LOG_FILE="/var/log/ssh-hardener.log"

# Logging function
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

log_warn() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING:${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR:${NC} $1" | tee -a "$LOG_FILE"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

log "Starting SSH Hardener Script..."

# Create backup directory
mkdir -p "$BACKUP_DIR"
log "Created backup directory: $BACKUP_DIR"

# Backup existing configurations
backup_config() {
    if [[ -f "$1" ]]; then
        cp "$1" "$BACKUP_DIR/"
        log "Backed up: $1"
    fi
}

backup_config "/etc/ssh/sshd_config"
backup_config "/etc/ufw/default"
backup_config "/etc/fail2ban/jail.local" 2>/dev/null || true

# Update system packages
log "Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq

# Install required packages
log "Installing required packages..."
apt-get install -y -qq ufw fail2ban

# Generate ED25519 SSH key pair for the current user
generate_ssh_keys() {
    local ssh_dir="/root/.ssh"
    local key_file="$ssh_dir/id_ed25519"
    
    # Check if key already exists
    if [[ -f "$key_file" ]]; then
        log_warn "SSH key already exists at $key_file, skipping generation"
        return 0
    fi
    
    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
    
    log "Generating ED25519 SSH key pair..."
    ssh-keygen -t ed25519 -f "$key_file" -N "" -C "root@$(hostname)"
    chmod 600 "$key_file"
    chmod 644 "${key_file}.pub"
    
    # Add to authorized_keys if not already present
    if [[ ! -f "$ssh_dir/authorized_keys" ]]; then
        touch "$ssh_dir/authorized_keys"
        chmod 600 "$ssh_dir/authorized_keys"
    fi
    
    cat "${key_file}.pub" >> "$ssh_dir/authorized_keys"
    log "SSH key generated and added to authorized_keys"
}

generate_ssh_keys

# Configure SSH
configure_ssh() {
    log "Configuring SSH..."
    
    # Backup original sshd_config
    cp /etc/ssh/sshd_config "$BACKUP_DIR/sshd_config.original"
    
    # Create new sshd_config with security best practices
    cat > /etc/ssh/sshd_config << EOF
# SSH Hardened Configuration - Generated by Crusty System
# Port configuration
Port $SSH_PORT

# Protocol and authentication
Protocol 2
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Key algorithms
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

# Security settings
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server

# Connection settings
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60
MaxAuthTries 3
MaxStartups 10:30:60

# Logging
SyslogFacility AUTH
LogLevel VERBOSE
EOF
    
    log "SSH configuration updated"
}

configure_ssh

# Configure UFW Firewall
configure_firewall() {
    log "Configuring UFW firewall..."
    
    # Reset UFW to defaults
    ufw --force reset
    
    # Set default policies
    ufw default deny incoming
    ufw default allow outgoing
    
    # Allow SSH on custom port
    ufw allow "$SSH_PORT"/tcp comment 'SSH'
    
    # Enable logging
    ufw logging on
    
    # Enable UFW
    ufw --force enable
    
    log "UFW firewall configured - SSH allowed on port $SSH_PORT"
}

configure_firewall

# Configure Fail2ban
configure_fail2ban() {
    log "Configuring Fail2ban..."
    
    # Create jail.local configuration
    cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
# Ban duration (10 minutes)
bantime = 600

# Time window for counting failures
findtime = 600

# Number of failures before ban
maxretry = 3

# Backend for log monitoring
backend = auto

# Email notifications (optional - configure if needed)
# destemail = your-email@example.com
# sendername = Fail2Ban
# mta = sendmail

[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600
EOF
    
    # Enable and restart fail2ban
    systemctl enable fail2ban
    systemctl restart fail2ban
    
    log "Fail2ban configured and started"
}

configure_fail2ban

# Configure automatic updates
configure_auto_updates() {
    log "Configuring automatic updates..."
    
    # Install unattended-upgrades if not present
    apt-get install -y -qq unattended-upgrades
    
    # Configure unattended-upgrades
    cat > /etc/apt/apt.conf.d/20auto-upgrades << EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
EOF
    
    # Configure which packages to update automatically
    cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

Unattended-Upgrade::Package-Blacklist {
    // Add packages to exclude from automatic updates
};

Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF
    
    # Add weekly update cron job at 2:00 AM
    cat > /etc/cron.d/crusty-auto-update << EOF
# Crusty System - Weekly automatic updates at 2:00 AM
0 2 * * 0 root /usr/bin/apt-get update && /usr/bin/apt-get upgrade -y >> /var/log/crusty-update.log 2>&1
EOF
    chmod 644 /etc/cron.d/crusty-auto-update
    
    log "Automatic updates configured (weekly at 2:00 AM)"
}

configure_auto_updates

# Restart SSH service
log "Restarting SSH service..."
systemctl restart sshd

# Display summary
echo ""
echo "=========================================="
log "SSH Hardening Complete!"
echo "=========================================="
echo ""
echo -e "${GREEN}Configuration Summary:${NC}"
echo "  - SSH Port: $SSH_PORT"
echo "  - Root Login: Disabled"
echo "  - Password Authentication: Disabled"
echo "  - Key-based Authentication: Enabled"
echo "  - Firewall: UFW enabled"
echo "  - Intrusion Prevention: Fail2ban active"
echo "  - Automatic Updates: Weekly at 2:00 AM"
echo ""
echo -e "${YELLOW}SSH Connection Info:${NC}"
echo "  ssh -p $SSH_PORT root@$(hostname -I | awk '{print $1}')"
echo ""
echo -e "${GREEN}Public Key (add this to your SSH client):${NC}"
cat /root/.ssh/id_ed25519.pub
echo ""
echo -e "${YELLOW}Private Key Location:${NC}"
echo "  /root/.ssh/id_ed25519"
echo ""
echo -e "${YELLOW}Backup Location:${NC}"
echo "  $BACKUP_DIR"
echo ""
echo -e "${YELLOW}Log File:${NC}"
echo "  $LOG_FILE"
echo ""
echo -e "${RED}IMPORTANT: Save your SSH keys before closing this session!${NC}"
echo ""
